apiVersion: v1
kind: Service
metadata:
  name: url-shortener-api-service
spec:
  type: LoadBalancer
  selector:
    app: url-shortener-api
  ports:
    - port: 5000
      targetPort: 47000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-api
spec:
  selector:
    matchLabels:
      app: url-shortener-api
  replicas: 5 # type how many pod you want to run
  template:
    metadata:
      labels:
        app: url-shortener-api
    spec:
      containers:
        - name: url-shortener-api
          image: mustafalaca/url_shortener_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 47000
